Vinny/response ue test kit
DISHDevEx/openverso-charts pull request #3
Opened 2023-03-20 06:00 UTC by vinayakSharm

Adding charts for large scale UE deployment.

Adding main response readme to ease creation of environment.

Adding response_ue_test_kit to enable modular and reusable test case generation.

2023-03-22 16:30 UTC, RemoNona commented on response_ue_test_kit/UE_TEST_KIT.md
> +python ping_test_creation.py
Should be `curl_test_creation`

2023-03-22 16:33 UTC, RemoNona commented on response_ue_test_kit/ping_test_creation.py
> +    ##load test_case_values json to read in the test case paremeters
`# Load test_case_values json to read in the test case parameters`

typo in parameters. format of comment should probably be like the example above.

https://peps.python.org/pep-0008/#comments

2023-03-22 16:34 UTC, RemoNona commented on response_ue_test_kit/ping_test_creation.py
> +    inputs:none
aim for uniform spacing in docstring params

2023-03-22 16:46 UTC, RemoNona commented on response_ue_test_kit/ping_test_creation.py
> +    num_of_ues = data_emulation_values["ueBatchSize"]
personal preference: why type `num_of_ues` if`num_ues` makes equal sense.

2023-03-22 16:55 UTC, RemoNona commented on response_ue_test_kit/ping_test_creation.py
> +        ##randomly select a spacing interval to ensure we dont overwhelm any servers
I don't think 'we' should be in code comments.

Consider:
`# Randomly select a spacing interval to avoid overwhelming website servers.` 

Or something similar

2023-03-22 16:57 UTC, RemoNona commented on response_ue_test_kit/ping_test_creation.py
> +        script.append(f"ping -I uesimtun{i} {rando_website}  -s {packet_size_bytes} -i {interval} -c {num_of_pings} & \n")
I don't know if it's on purpose (it probably doesn't matter), but there's an extra space before `-s`.

2023-03-22 16:58 UTC, RemoNona commented on response_ue_test_kit/ping_test_creation.py
> +    master_test_file = open('test_case_values.json')
You open the json file but you don't `.close()` it

2023-03-22 17:09 UTC, RemoNona commented on response_ue_test_kit/curl_test_creation.py
> +Module to create a script to emulate curl requests from UEs emulated via UERANSIM deployment
Make sure your docstrings have proper punctuation (missing period at end).

2023-03-22 17:09 UTC, RemoNona commented on response_ue_test_kit/curl_test_creation.py
> +    ##load test_case_values json to read in the test case paremeters
Fix comment format

2023-03-22 17:10 UTC, RemoNona commented on response_ue_test_kit/curl_test_creation.py
> +    print("curl.sh written to simulation_scripts/curl.sh")
Same comments about success/error print outs

2023-03-22 17:11 UTC, RemoNona commented on response_ue_test_kit/UE_TEST_KIT.md
> +### Set up many ue environment
"Setup Multi-UE Environment"  sounds more formal

2023-03-22 17:17 UTC, RemoNona commented on response_ue_test_kit/UE_TEST_KIT.md
> +
Prerequisites 
-helm
-kubectl

2023-03-22 17:43 UTC, RemoNona commented on response_ue_test_kit/UE_TEST_KIT.md
> +(1)install open5gs (2.5 mins)
add space between (1) and install so it's uniform across the readme

2023-03-22 17:48 UTC, RemoNona commented on response_ue_test_kit/UE_TEST_KIT.md
> +Inside the terminal for the populate pod copy paste contents of:  openverso-charts/response_ue_test_kit/simulation_scripts/ue_populate.sh
This should be a step

2023-03-22 21:30 UTC, RemoNona commented on RESPONSE_README.md
> +1. Set up your machine with the following CLI tools:
This is what these lines look like in markdown. You need an extra empty row. 
`Set up your machine with the following CLI tools: AWS CLI`

I suggest using "- "
````
Set up your machine with the following CLI tools: 
- AWS CLI
- Kubectl
- Helm

2023-03-22 21:34 UTC, RemoNona commented on RESPONSE_README.md
> +    ```console
Are these separate commands? If so I would suggest breaking them into separate code blocks. User intuition would be to copy anything in the code block and paste. The code block also has a "copy" icon when you hover over it and would copy the whole block.

There are other code blocks in this format, check them out too.

2023-03-22 21:36 UTC, RemoNona commented on RESPONSE_README.md
> +1. Set up your machine with the following CLI tools:
Same comment as line 5

2023-03-22 21:37 UTC, RemoNona commented on RESPONSE_README.md
> +
Looks like some formatting was missed from here to line 109

2023-03-22 21:39 UTC, RemoNona commented on charts/respons/gnb-noues-values.yaml
> +
Extra empty line here

2023-03-22 21:40 UTC, RemoNona commented on charts/respons/gnb-ues450-values.yaml
> +
Theres an extra empty line here

2023-03-22 21:41 UTC, RemoNona commented on charts/respons/gnb_no_ues_values.yaml
> +
Maybe it's standard to have two empty lines after these key:value pairs. If not you could remove

2023-03-22 21:41 UTC, RemoNona commented on response_ue_test_kit/UE_TEST_KIT.md
> +(1)install open5gs (2.5 mins)
You can use the "1. " in markdown for better numbering format.

2023-03-22 21:50 UTC, RemoNona commented on response_ue_test_kit/curl_test_creation.py
Consider fixing these issues.

************* Module curl_test_creation
curl_test_creation.py:13:0: C0303: Trailing whitespace (trailing-whitespace)
curl_test_creation.py:14:68: C0303: Trailing whitespace (trailing-whitespace)
curl_test_creation.py:18:0: C0303: Trailing whitespace (trailing-whitespace)
curl_test_creation.py:23:0: C0303: Trailing whitespace (trailing-whitespace)
curl_test_creation.py:26:35: C0303: Trailing whitespace (trailing-whitespace)
curl_test_creation.py:31:0: C0301: Line too long (125/100) (line-too-long)
curl_test_creation.py:37:0: C0303: Trailing whitespace (trailing-whitespace)
curl_test_creation.py:42:0: C0304: Final newline missing (missing-final-newline)
curl_test_creation.py:15:23: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
curl_test_creation.py:33:20: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
curl_test_creation.py:41:11: W0703: Catching too general exception Exception (broad-except)

-----------------------------------
Your code has been rated at 5.00/10

2023-03-22 21:51 UTC, RemoNona commented on response_ue_test_kit/ping_test_creation.py
Consider making the changes below.

************* Module ping_test_creation
ping_test_creation.py:8:22: C0303: Trailing whitespace (trailing-whitespace)
ping_test_creation.py:13:0: C0303: Trailing whitespace (trailing-whitespace)
ping_test_creation.py:14:68: C0303: Trailing whitespace (trailing-whitespace)
ping_test_creation.py:18:0: C0303: Trailing whitespace (trailing-whitespace)
ping_test_creation.py:25:0: C0303: Trailing whitespace (trailing-whitespace)
ping_test_creation.py:26:0: C0301: Line too long (120/100) (line-too-long)
ping_test_creation.py:28:35: C0303: Trailing whitespace (trailing-whitespace)
ping_test_creation.py:33:0: C0301: Line too long (122/100) (line-too-long)
ping_test_creation.py:39:0: C0303: Trailing whitespace (trailing-whitespace)
ping_test_creation.py:44:0: C0304: Final newline missing (missing-final-newline)
ping_test_creation.py:15:23: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
ping_test_creation.py:35:20: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
ping_test_creation.py:20:4: W0612: Unused variable 'num_of_ues' (unused-variable)
ping_test_creation.py:43:11: W0703: Catching too general exception Exception (broad-except)

-----------------------------------
Your code has been rated at 4.17/10

2023-03-22 21:52 UTC, RemoNona commented on response_ue_test_kit/ue_populate_creation.py
Consider making these changes.
************* Module ue_populate_creation
ue_populate_creation.py:2:0: C0301: Line too long (135/100) (line-too-long)
ue_populate_creation.py:5:11: C0303: Trailing whitespace (trailing-whitespace)
ue_populate_creation.py:12:0: C0303: Trailing whitespace (trailing-whitespace)
ue_populate_creation.py:13:68: C0303: Trailing whitespace (trailing-whitespace)
ue_populate_creation.py:17:0: C0303: Trailing whitespace (trailing-whitespace)
ue_populate_creation.py:19:0: C0303: Trailing whitespace (trailing-whitespace)
ue_populate_creation.py:21:0: C0303: Trailing whitespace (trailing-whitespace)
ue_populate_creation.py:25:0: C0301: Line too long (166/100) (line-too-long)
ue_populate_creation.py:28:0: C0301: Line too long (165/100) (line-too-long)
ue_populate_creation.py:31:0: C0301: Line too long (164/100) (line-too-long)
ue_populate_creation.py:34:0: C0301: Line too long (163/100) (line-too-long)
ue_populate_creation.py:37:0: W0311: Bad indentation. Found 13 spaces, expected 12 (bad-indentation)
ue_populate_creation.py:49:0: C0304: Final newline missing (missing-final-newline)
ue_populate_creation.py:24:11: R1716: Simplify chained comparison between the operands (chained-comparison)
ue_populate_creation.py:27:11: R1716: Simplify chained comparison between the operands (chained-comparison)
ue_populate_creation.py:30:11: R1716: Simplify chained comparison between the operands (chained-comparison)
ue_populate_creation.py:33:11: R1716: Simplify chained comparison between the operands (chained-comparison)
ue_populate_creation.py:14:23: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
ue_populate_creation.py:40:20: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
ue_populate_creation.py:48:11: W0703: Catching too general exception Exception (broad-except)

-----------------------------------
Your code has been rated at 2.59/10

2023-03-22 21:58 UTC, RemoNona commented on response_ue_test_kit/ue_populate_creation.py
> +    inputs:none
reformat based on other commends and RESPONs standard.

2023-03-22 22:00 UTC, RemoNona requested changes
Agreed with Vinny to make a new PR for Pytests

2023-03-23 15:28 UTC, RemoNona commented
`helm uninstall ueransim-ues-first-batch` doesn't work. I get `Error: INSTALLATION FAILED: cannot re-use a name that is still in use`
https://stackoverflow.com/questions/61387463/uninstall-release-not-loaded-new-release-not-found-chart-deployed-using-hel
Comment in link says to try:
`helm uninstall ueransim-ues-first-batch -n openverso`
`helm uninstall {releaseName} -n {releaseNameSpace}`
Which works

2023-04-03 16:05 UTC, vinayakSharm commented on RESPONSE_README.md
> +1. Set up your machine with the following CLI tools:
done

2023-04-03 16:10 UTC, vinayakSharm commented on RESPONSE_README.md
> +1. Set up your machine with the following CLI tools:
done

2023-04-03 16:31 UTC, vinayakSharm commented on RESPONSE_README.md
> +1. Set up your machine with the following CLI tools:
done

2023-04-03 16:31 UTC, vinayakSharm commented on RESPONSE_README.md
> +
done

2023-04-03 16:33 UTC, vinayakSharm commented on RESPONSE_README.md
> +    ```console
done

2023-04-03 16:33 UTC, vinayakSharm commented on RESPONSE_README.md
> +kubectl -n openverso logs deployment/ueransim-gnb
done

2023-04-03 16:35 UTC, vinayakSharm commented on charts/respons/gnb-noues-values.yaml
> +
done

2023-04-03 16:35 UTC, vinayakSharm commented on charts/respons/gnb-noues-values.yaml
> +
done

2023-04-03 16:35 UTC, vinayakSharm commented on charts/respons/gnb-ues450-values.yaml
> +
done

2023-04-03 16:40 UTC, vinayakSharm commented on charts/respons/gnb_no_ues_values.yaml
> +
done

2023-04-03 16:42 UTC, vinayakSharm commented on response_ue_test_kit/ping_test_creation.py
> +        script.append(f"ping -I uesimtun{i} {rando_website}  -s {packet_size_bytes} -i {interval} -c {num_of_pings} & \n")
done

2023-04-03 16:42 UTC, vinayakSharm commented on response_ue_test_kit/ping_test_creation.py
> +    master_test_file = open('test_case_values.json')
Using a with open() statement will automatically close a file once the block has completed.

https://www.learndatasci.com/solutions/python-close-file/#:~:text=Using%20a%20with%20open(),program%20is%20using%20the%20file.

2023-04-03 16:43 UTC, vinayakSharm commented on response_ue_test_kit/ping_test_creation.py
> +    master_test_file = open('test_case_values.json')
discarded

2023-04-03 16:44 UTC, vinayakSharm commented on response_ue_test_kit/ping_test_creation.py
> +    except Exception as e:
done

2023-04-03 16:44 UTC, vinayakSharm commented on response_ue_test_kit/curl_test_creation.py
> +Module to create a script to emulate curl requests from UEs emulated via UERANSIM deployment
done

2023-04-03 16:47 UTC, vinayakSharm commented on response_ue_test_kit/curl_test_creation.py
> +    inputs:none
done

2023-04-03 16:49 UTC, vinayakSharm commented on response_ue_test_kit/curl_test_creation.py
> +    print("curl.sh written to simulation_scripts/curl.sh")
done

2023-04-03 16:50 UTC, vinayakSharm commented on response_ue_test_kit/UE_TEST_KIT.md
> +### Set up many ue environment
done

2023-04-03 16:50 UTC, vinayakSharm commented on response_ue_test_kit/UE_TEST_KIT.md
> +
done

2023-04-03 16:55 UTC, vinayakSharm commented on response_ue_test_kit/UE_TEST_KIT.md
> +(1)install open5gs (2.5 mins)
done

2023-04-03 16:57 UTC, vinayakSharm commented on response_ue_test_kit/UE_TEST_KIT.md
> +Inside the terminal for the populate pod copy paste contents of:  openverso-charts/response_ue_test_kit/simulation_scripts/ue_populate.sh
done

2023-04-03 17:00 UTC, vinayakSharm commented on response_ue_test_kit/ping_test_creation.py
> +    print("ping.sh written to simulation_scripts/ping.sh")
done

2023-04-03 17:25 UTC, vinayakSharm commented on response_ue_test_kit/ping_test_creation.py
update: 

************* Module respons_ue_test_kit.ping_test_creation
ping_test_creation.py:38:0: C0301: Line too long (110/100) (line-too-long)
ping_test_creation.py:16:23: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
ping_test_creation.py:41:20: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
ping_test_creation.py:16:23: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
ping_test_creation.py:41:20: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
ping_test_creation.py:50:11: W0718: Catching too general exception Exception (broad-exception-caught)
------------------------------------------------------------------
Your code has been rated at 7.60/10

- First line too long error is ignored because the formatting needs to be kept to write lines to a .sh file. 
- Using open and not specifying encoding is on purpose because I am opening and then performing a json load , not a read file. 
- Not using with for the same reason
- General exception kept, because there may be a variety of issues, printing the general error will help user debug.

2023-04-03 17:47 UTC, vinayakSharm commented on response_ue_test_kit/curl_test_creation.py
Module respons_ue_test_kit.curl_test_creation
curl_test_creation.py:34:0: C0301: Line too long (114/100) (line-too-long)
curl_test_creation.py:17:23: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
curl_test_creation.py:37:20: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
curl_test_creation.py:17:23: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
curl_test_creation.py:37:20: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
curl_test_creation.py:46:11: W0718: Catching too general exception Exception (broad-exception-caught)

-----------------------------------
Your code has been rated at 7.27/10

- First line too long error is ignored because the formatting needs to be kept to write lines to a .sh file.
- Using open and not specifying encoding is on purpose because I am opening and then performing a json load , not a read file.
- Not using "with" for the same reason
- General exception kept, because there may be a variety of issues, printing the general error will help user debug.

2023-04-03 20:34 UTC, vinayakSharm commented on response_ue_test_kit/ue_populate_creation.py
ue_populate_creation.py:29:0: C0301: Line too long (155/100) (line-too-long)
ue_populate_creation.py:34:0: C0301: Line too long (154/100) (line-too-long)
ue_populate_creation.py:39:0: C0301: Line too long (153/100) (line-too-long)
ue_populate_creation.py:44:0: C0301: Line too long (152/100) (line-too-long)
ue_populate_creation.py:15:23: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
ue_populate_creation.py:50:20: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
ue_populate_creation.py:15:23: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
ue_populate_creation.py:50:20: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
ue_populate_creation.py:59:11: W0718: Catching too general exception Exception (broad-exception-caught)

------------------------------------------------------------------
Your code has been rated at 6.67/10


Validation for breaking the pylint rules above: 

First line too long error is ignored because the formatting needs to be kept to write lines to a .sh file. More legible this way. 

Using open and not specifying encoding is on purpose because I am opening and then performing a json load , not a read file.

Not using 'with' for the same reason

General exception kept, because there may be a variety of issues, printing the general error will help user debug.

2023-04-03 20:45 UTC, vinayakSharm commented
https://github.com/DISHDevEx/openverso-charts/pull/3/files#issuecomment-1481401575

resolved:  helm uninstall ueransim-ues-first-batch -n openverso and helm uninstall ueransim-ues-first-batch are the same command. Pls check which namespace you are working out of. -n is the namespace flag, does not change the command.

2023-04-03 20:49 UTC, vinayakSharm reviewed
incorporated results from tomers PR

2023-04-03 22:16 UTC, vinayakSharm commented on response_ue_test_kit/ping_test_creation.py
> +    inputs:none
idk why it hid this, but i will update my code to reflect this standard. brief moment here.

2023-04-03 22:20 UTC, vinayakSharm commented on response_ue_test_kit/ping_test_creation.py
> +    ##load test_case_values json to read in the test case paremeters
done

2023-04-03 22:20 UTC, vinayakSharm commented on response_ue_test_kit/ping_test_creation.py
> +    inputs:none
added this to all py files

2023-04-03 22:20 UTC, vinayakSharm commented on response_ue_test_kit/ping_test_creation.py
> +    num_of_ues = data_emulation_values["ueBatchSize"]
changed

2023-04-03 22:21 UTC, vinayakSharm commented on response_ue_test_kit/ping_test_creation.py
> +    list_of_websites_to_ping = data_emulation_values["webisteList"]
fixed

2023-04-03 22:22 UTC, vinayakSharm commented on response_ue_test_kit/ping_test_creation.py
> +        ##randomly select a spacing interval to ensure we dont overwhelm any servers
done

2023-04-03 22:23 UTC, vinayakSharm commented
all suggestions have been incorporated. lmk if we can proceed to merge @RemoNona thx :)

2023-04-04 22:49 UTC, RemoNona approved these changes
You did it! :) <3

2023-04-04 22:50 UTC, merged